// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtusxk7e-CtyhCbMLbNYAGTODoyEOCsdw',
    appId: '1:491525592414:web:bc44ab8d5c442facbbabcf',
    messagingSenderId: '491525592414',
    projectId: 'hawa-hawa-final',
    authDomain: 'hawa-hawa-final.firebaseapp.com',
    storageBucket: 'hawa-hawa-final.firebasestorage.app',
    measurementId: 'G-TDJVHEQ28V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrzecVEJiNDJsVaVPPNTyBXg7HxnMXxA',
    appId: '1:491525592414:android:ab55f6b05f7c5a29bbabcf',
    messagingSenderId: '491525592414',
    projectId: 'hawa-hawa-final',
    storageBucket: 'hawa-hawa-final.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtusxk7e-CtyhCbMLbNYAGTODoyEOCsdw',
    appId: '1:491525592414:web:9094e220e6b92c0dbbabcf',
    messagingSenderId: '491525592414',
    projectId: 'hawa-hawa-final',
    authDomain: 'hawa-hawa-final.firebaseapp.com',
    storageBucket: 'hawa-hawa-final.firebasestorage.app',
    measurementId: 'G-3RC2VR8W71',
  );
}
